#!/usr/bin/env ruby
puts `gobump show`
puts "next version is?"
next_version = gets.chomp

puts `gobump set #{next_version} -w`

puts `git c -am "version up to #{next_version}"`
puts `git tag v#{next_version}`
puts `git push && git push --tags`

puts `goxc -pv v#{next_version}`
puts `ghr v#{next_version} dist/v#{next_version}`
